name: Feature request
description: Suggest an idea or improvement
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Problem
      description: What problem would this feature solve?
      placeholder: I’m frustrated when ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposal
      description: What would you like to see happen?
      placeholder: Describe the solution you’d like.
  - type: textarea
    attributes:
      label: Alternatives
      description: Any alternative solutions you’ve considered?
  - type: textarea
    attributes:
      label: Additional context
      description: Links, screenshots, examples.
